In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [5]:
# neural network continue

import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# output = np.dot(inputs, weights)) + biases # will casue error because of the shape of inputs and weights are not the same shape (3,4) and (3,4) respectively 
output = np.dot(inputs, np.array(weights).T) + biases # will be solved by takin the Transpose of weights (3,4) and (4,3) respectively 
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [9]:
# neural network continue

import numpy as np

inputs = [[2, 2.23, 3.54, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2


print(layer2_outputs)
print('###'*9)
print(layer1_outputs)

[[ 0.338996 -0.971119 -1.744268]
 [ 0.2434   -2.7332   -5.7633  ]
 [-0.99314   1.41254  -0.35655 ]]
###########################
[[ 4.914   1.6411  2.1547]
 [ 8.9    -1.81    0.2   ]
 [ 1.41    1.051   0.026 ]]


**Using Classes**

In [14]:
# neural network continue

import numpy as np

inputs = [[2, 2.23, 3.54, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

class Dense_layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    
layer1 = Dense_layer(4, 5)
layer2 = Dense_layer(5, 2)

layer1.forward(inputs)
print(layer1.output)
print('_______'*9)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.59113051 -0.40835442  0.19768734  0.1321785   0.05173439]
 [-1.19792017 -0.26632241 -0.07392264 -0.3727955   0.51639452]
 [-0.60578311  0.00656296  0.21820498  0.66670936 -0.5673447 ]]
_______________________________________________________________
[[-0.25143524 -0.00754454]
 [-0.51967418  0.01123128]
 [-0.07438422 -0.08407126]]
